{% set name = "semi-ate-spyder" %}
{% set version = "1.0.12" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/semi-ate-spyder-{{ version }}.tar.gz
  sha256: 3ca325611d46ae32171c85415e579ece9819b676cb06fb6ac7c2db58023d6fe1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - numpy
    - pydantic
    - python >=3.8
    - qtawesome
    - semi-ate-common
    - semi-ate-plugins
    - semi-ate-project-database
    - semi-ate-sammy
    - spyder >=5.3

test:
  imports:
    - ate_spyder
    - ate_spyder.widgets
  commands:
    - pip check  # [linux or win]
  requires:
    - pip
    # This build of numpydoc has broken requirements
    - numpydoc !=1.2.1=*_0

about:
  home: https://pypi.org/project/semi-ate-spyder/
  summary: Spyder ate plugin for working with ATE projects
  license: GPL-2.0-only
  license_file: ate_spyder/LICENSE.txt

extra:
  recipe-maintainers:
    - nerohmot
