{% set name = "semi-ate-spyder" %}
{% set version = "1.0.17" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 708fdad38204d636acc4b1040b385ad0d4e4df291d65bf5bf3f50c2df1c9d096

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - numpy
    - pydantic
    - python >=3.8
    - qtawesome
    - semi-ate-common
    - semi-ate-plugins
    - semi-ate-project-database
    - semi-ate-sammy
    - spyder >=5.3
    - qtpy
    - pyqt
    - pluggy
    - watchdog
    - cookiecutter
    - setuptools

test:
  imports:
    - ate_spyder
    - ate_spyder.widgets
  commands:
    - pip check  # [linux or win]
  requires:
    - pip
    # This build of numpydoc has broken requirements
    - numpydoc !=1.2.1=*_0
    - setuptools

about:
  home: https://pypi.org/project/semi-ate-spyder/
  summary: Spyder ate plugin for working with ATE projects
  license: GPL-2.0-only
  license_file: ate_spyder/LICENSE.txt

extra:
  recipe-maintainers:
    - nerohmot
    - heli2src
    - Zlin526F
